### ISSUE TITLE
Lack of legibility and URL bugs

### ISSUE THREAD

**Issue by pr4j3sh** [leekli/voyager#1]
I'm listing a few suggestions and bugs I came across.

## Suggestions

- cannot scroll up
- no lower scrolling limit
- text rendered in browser window is not legible
- renders javascript code in browser window
- no menu on browser window(to show action buttons and what all features browser support)

## Bugs

- if no url is provided, throws `IndexError` (can display a warning, nudging user what to do)
- if only domain is provided without `http/https`, throws `ValueError` (can display a warning, nudging user what to do)
- if incomplete/invalid url is provided, throws `socket.gaierror` (can display a warning, nudging user what to do)

I was looking for contributing in your project. If you don't mind I can help you fix these bugs and would love to improve it more to make it more work like a browser.

**Comment by leekli** [comment]
Hey :-) 

Thanks for your comments. This is just a little hobby repo for me, where I'm using a book to help me build a browser chapter by chapter so I'm not looking to make it a big thing, it's just something I'm slowly working on to help me understand browsers, protocols and Python. I appreciate the time you've taken with it, but it's not a project I'm looking for contributors with at the moment I'm afraid as I want to continue working through it on my own so I don't miss out on anything from the book.

Thanks again.
